name: translate test
on:
  pull_request:
    branches: 
      - m0a/feature/**

defaults:
  run:
    shell: bash

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Setup Zig
      uses: goto-bus-stop/setup-zig@v1.3.0
      with:
        version: master
    - run: LANG=ja_JP.UTF-8 && lang_patches/translate.sh
    - run: patches/eowyn.sh
